base_url = "./"
title = "Sample API"
description = "Powerful, Reliable, and Easy to Integrate API"
compile_sass = false
build_search_index = false

[extra]
# Contact Information
email_contact = "contact@example.com"
email_support = "support@example.com"
email_business = "business@example.com"

# Social Links
github = "https://github.com/example"
twitter = "https://twitter.com/example"
linkedin = "https://linkedin.com/company/example"

# External Links
docs_url = "https://docs.example.com"
signup_url = "https://app.example.com/signup"
pricing_url = "https://example.com/pricing"
