name = "OnePageAPI"
description = "A template for simple single page API introduction"
# An optional tags to allow quick search
tags = []
license = "GPL-3.0"
homepage = "https://github.com/VishalRashmika/OnePageAPI"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = "https://vishalrashmika.github.io/OnePageAPI"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Vishal Rashmika"
homepage = "https://vishalrashmika.com"